[package]
name = "bench"
version = "0.1.0"
authors = ["Carl Pearson <carl.w.pearson@gmail.com>"]

[[bin]]
name = "ex1"
path = "examples/ex1.rs"

[dependencies]
lazy_static = "1.0"
num = "0.1"
regex = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"

